apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres15
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mariosangut/2-asir-bil-pasir-mario-sanchez-gutierrez.git' 
    targetRevision: HEAD
    path: apps/database
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true