apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tls-certs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mariosangut/2-asir-bil-pasir-mario-sanchez-gutierrez.git'
    targetRevision: HEAD
    path: infra/tls-certs
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
